site_name: Herpesvirus Genomics Wiki
site_description: Herpesvirus Genomics Wiki
site_url: https://depledgelab.github.io/HerpesvirusGenomicsWiki/

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

nav:
  - Home: index.md

  - Getting Started: 
      - getting-started/index.md

  - Wet lab:
      - wet-lab/index.md

  - DNA analyses:
      - dna/index.md

  - RNA analyses:
      - rna/index.md
      - Nanopore Direct RNA Sequencing (DRS): 
        - rna/nanopore-drs/index.md        
        - Multiplexing approaches: rna/nanopore-drs/multiplexing.md
        - Poly(A) tail analyses: rna/nanopore-drs/poly-a-tails.md
        - RNA modification detection: rna/nanopore-drs/rna-modifications.md
        - Additional applications of DRS: rna/nanopore-drs/alternative-apps.md   

  - References:
      - references/index.md
      #- Glossary: reference/glossary.md